dist: xenial
language: java
sudo: false
jdk: openjdk16
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=murilohenzo_bookstore-manager -Dsonar.organization=murilohenzo -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=61f619d9174f72189735b5931ac3c856ba281e2b -Djacoco.skip=true
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache