spring:
  # Database
  datasource:
    # url de conexão do banco de dados
    url: jdbc:mysql://localhost/bookstore_db?useTimezone=true&serverTimezone=America/Sao_Paulo
    # usuário e senha de conexão com o banco de dados
    username: root
    password: 12345
  # JPA properties
  jpa:
    # deixamos o hibernate responsável por ler nossas entidades e criar as tabelas do nosso banco de dados automaticamente
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: true
    generate-ddl: true

# Logger configuration
logging:
  level:
    br:
      com:
        murilohenzo: DEBUG
# Server configuration
server:
  port: 8080 #set your port